enable-module-update = true # set this to false if you do not want to receive updates for the module
# parallel-jobs = 1 
# NOTE: parallel-jobs MUST BE 1 if using `arch="both"` to avoid download errors.
# see https://github.com/nvbangg/morphe-builder/blob/main/CONFIG.md for more detailed explanations

[Instagram]
patches-source = "crimera/piko"
patches-version = "dev"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"

